[package]
name = "crypto-native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
neon = "0.10"
tokio = { version = "1.0", features = ["full"] }
ring = "0.16"
x25519-dalek = "2.0"
ed25519-dalek = "2.0"
hkdf = "0.12"
aes-gcm = "0.10"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
